const Animation = () => { 
    return (
        <section className="article-section">
            <h3 className="section-heading">Animation</h3>
            <ul className="related-career-history">
                <li>Education: Introduction to 3D Animation (B+) | Certificate of MangAnime Elementary Drawing (amps, Japanese Duly Qualified)</li>
                <li>Projects: CLEARgo.com, Midea Eureka, Heybike</li>
            </ul>
            <p>Familiar with web animation which adds the dimension of time to the GUI of a web page in order to convey information organized by data, feedback, and aesthetic qualities to end-users through storytelling.</p>
            <p>Trained by Japanese traditional animation education and learned animation theory and practical skills which can transfer to web animation development.</p>
            <section className="article-section">
                <h4>Animation Types</h4>
                <ul id="animation-types">
                    <li><b>Straight Ahead Animation</b>: This is a difficult technique where the UX/UI designer or frontend developer generates a series of frames in sequence, one after the other. However, it is the most experimental approach which allows us to make decisions and change ideas as we want. I created straight ahead animation with image sequences generated by UX/UI designer for Heybike X-Series page header.</li>
                    <li><b>Pose-to-Pose Animation</b>: This is the most popular approach applied in frontend web development, as it forms the core of CSS transitions and keyframes. By defining the significant points in a series of actions, we can separate the animation into keyframes and in-betweens. Notably, many web standard methods handle the tweening for us automatically.</li>
                </ul>
            </section>
            <section className="article-section">
                <h4>Keyframing and Tweening</h4>
                <p>An animation can be breakdown into frames including keyframes, breakdowns, and in-betweens.</p>
                <p>Each frame of an action should be number in the top-right corner on the animation paper. We should always circle keyframe numbers and put parenthesis around breakdown number.</p>
                <p>With the frames numbered, we should create an action chart with a direction from left (first key) to right (next key) on the first keyframe. This chart indicates how many in-betweens are needed and how they will be spaced between two keyframes.</p>
                <ul id="tweening-components">
                    <li><b>Keyframes</b>: Keyframes are the major scenes in an action where that action ceases or change direction.</li>
                    <li><b>In-betweens</b>: Keyframes are the major scenes in an action where that action ceases or change direction.</li>
                </ul>
            </section>
            <section className="article-section">
                <h4 className="section-heading">​Web Animation Methods</h4>
                <ul id="web-animation-methods">
                    <li><b>Transitions:</b> By applying the concept of finite-state machines (FSM), CSS fills in the in-betweens smoothly over a specified duration between two states.</li>
                    <li><b>Keyframes:</b> CSS keyframes implement the traditional animation theory of pose-to-pose since the frontend developer can break down the timeline into several phases by defining the significant points as keyframes.</li>
                    <li><b>setInterval:</b> A basic JavaScript timing method used to trigger animations at fixed intervals, though less efficient than requestAnimationFrame.</li>
                    <li><b>requestAnimationFrame:</b> The high-performance method for scripted animations, ensuring synchronization with the browser's refresh rate.</li>
                    <li><b>jQuery Effects:</b> jQuery provides simplification of commonly complex animation operations such as fade-in/out, slide-up/down, and animate, etc.</li>
                </ul>
            </section>
            <ul className="featured-works">
                <li>
                    <figure id="storybroad">
                        <img id="storybroad" src="https://cdn.shopify.com/s/files/1/0626/2253/1645/files/storyboard-of-graduation-project.png?v=1769440868" />
                        <figcaption>Storybroad of Graduation Project, 2019</figcaption>
                    </figure>
                </li>
                <li>
                    <figure id="keyframing">
                        <ul id="keyframe-works">
                            <li class="keyframe-work"><img src="https://cdn.shopify.com/s/files/1/0626/2253/1645/files/anime_1_A1.png?v=1769701806" /></li>
                            <li class="keyframe-work"><img src="https://cdn.shopify.com/s/files/1/0626/2253/1645/files/anime_1_A4.png?v=1769701810" /></li>
                            </ul>
                        <figcaption>Keyframing Practice, 2022</figcaption>
                    </figure>
                </li>
            </ul>
        </section>
    ); 
}; 

export default Animation;